package com.hireloop.backend.user.repository;

import com.hireloop.backend.user.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    
    // Derived query methods generated by Spring Data JPA
    Optional<User> findByEmail(String email);
    
    boolean existsByEmail(String email);
}